global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Triton Inference Server metrics
  - job_name: 'triton'
    static_configs:
      - targets: ['triton:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Preprocessing service metrics
  - job_name: 'preprocess-service'
    static_configs:
      - targets: ['preprocess-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Node exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s