name: "cifar10_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 32, 32 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

# Оптимизации для CPU
optimization {
  execution_accelerators {
    cpu_execution_accelerator : [ {
      name : "openvino"
    }]
  }
}

# Динамическое батчинг
dynamic_batching {
  max_queue_delay_microseconds: 100
  preferred_batch_size: [ 8, 16 ]
}

# Версии модели
version_policy: { all { }}

# Инстансы модели
instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]